openapi: 3.0.3
info:
  title: Uddaan Agencies Admin API
  version: 1.0.0
servers:
  - url: http://localhost:3000
paths:
  /health:
    get:
      summary: Health check
      responses:
        '200':
          description: OK
  /api/auth/login:
    post:
      summary: Login with email and password
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
              required: [email, password]
      responses:
        '200':
          description: Login response
  /api/auth/verify-2fa:
    post:
      summary: Verify TOTP 2FA code
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                code:
                  type: string
              required: [code]
      responses:
        '200':
          description: Verified
  /api/auth/logout:
    post:
      summary: Logout and clear cookies
      responses:
        '204':
          description: No content
  /api/auth/password-reset/request:
    post:
      summary: Request password reset
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email: { type: string }
              required: [email]
      responses:
        '204':
          description: Email sent
  /api/auth/password-reset/confirm:
    post:
      summary: Confirm password reset
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                token: { type: string }
                password: { type: string }
              required: [token, password]
      responses:
        '204':
          description: Password updated
  /api/jobs:
    get:
      summary: List jobs
      parameters:
        - in: query
          name: page
          schema: { type: integer }
        - in: query
          name: limit
          schema: { type: integer }
        - in: query
          name: q
          schema: { type: string }
        - in: query
          name: country
          schema: { type: string }
        - in: query
          name: status
          schema: { type: string }
      responses:
        '200': { description: OK }
    post:
      summary: Create job
      responses:
        '201': { description: Created }
  /api/jobs/{id}:
    get:
      summary: Get job by id
      parameters:
        - in: path
          name: id
          required: true
          schema: { type: string }
      responses:
        '200': { description: OK }
    patch:
      summary: Update job
      parameters:
        - in: path
          name: id
          required: true
          schema: { type: string }
      responses:
        '200': { description: OK }
    delete:
      summary: Delete job
      parameters:
        - in: path
          name: id
          required: true
          schema: { type: string }
      responses:
        '204': { description: No content }

  /api/applications:
  /api/admin/contacts:
    get:
      summary: List contacts (admin)
      parameters:
        - in: query
          name: page
          schema: { type: integer }
        - in: query
          name: limit
          schema: { type: integer }
        - in: query
          name: q
          schema: { type: string }
        - in: query
          name: status
          schema: { type: string }
      responses:
        '200': { description: OK }
    post:
      summary: Create contact (admin)
      responses:
        '201': { description: Created }
  /api/admin/contacts/{id}:
    get:
      summary: Get contact by id (admin)
      parameters:
        - in: path
          name: id
          required: true
          schema: { type: string }
      responses:
        '200': { description: OK }
    patch:
      summary: Update contact (admin)
      parameters:
        - in: path
          name: id
          required: true
          schema: { type: string }
      responses:
        '200': { description: OK }
    delete:
      summary: Delete contact (admin)
      parameters:
        - in: path
          name: id
          required: true
          schema: { type: string }
      responses:
        '204': { description: No content }
    post:
      summary: Submit job application (public)
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                jobId: { type: string, format: uuid }
                candidateName: { type: string }
                candidatePhone: { type: string }
                candidateEmail: { type: string, format: email }
              required: [jobId, candidateName, candidatePhone, candidateEmail]
      responses:
        '201': { description: Created }
